version: 2.1
commands:
  install_deps:
    steps:
      - run:
          name: Install dependencies
          command: |
            npm install

jobs:
  ci-build:
    docker:
      - image: circleci/node:lts
    environment:
      MOCHA_JUNIT_OUTPUT_DIR: test-output
    steps:
      - checkout 
      - install_deps
  
      - run:
          name: Run test-unit
          command: |
            mkdir -p test-output
            npm run test-unit 
            
            
  pack:
    docker:
      - image: circleci/node:lts
    environment:
      NODE_ENV: production
    steps:
      - checkout
      - install_deps
      - store_artifacts:
          path: ./

workflows:
  build-and-packge:
    jobs:
      - ci-build
    
      