version: 2.1
commands:
  install_deps:
    steps:
      - run:
          name: Install dependencies
          command: |
            npm install

jobs:
  ci-build:
    docker:
      - image: circleci/node:lts
    environment:
      MOCHA_JUNIT_OUTPUT_DIR: test-output
    steps:
      - checkout 
      - install_deps
      - run:
          name: Run lint
          command: npm run test-lint
      - run:
          name: Run unit tests
          command: |
            mkdir -p test-output
            npm run test-unit
            
      - run:
          name: Validate Coverage
          command: |
            npm run test-coverage

      - store_test_results:
          path: test-output

  pack:
    docker:
      - image: circleci/node:lts
    environment:
      NODE_ENV: production
    steps:
      - checkout
      - install_deps
      - store_artifacts:
          path: ./

workflows:
  build-and-packge:
    jobs:
      - ci-build
      